# Generated by Django 4.0.1 on 2022-02-07 16:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=django.contrib.auth.models.User, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('year_number', models.IntegerField(default=0)),
                ('month_number', models.IntegerField(default=0)),
                ('week_number', models.IntegerField(default=0)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('week_number', models.IntegerField(default=0)),
                ('month_number', models.IntegerField(default=0)),
                ('classification', models.CharField(blank=True, choices=[('RR', 'Road Race'), ('CR', 'Crit/Circuit Race'), ('TT', 'Time Trial'), ('HC', 'Hill Climb'), ('SP', 'Sportive'), ('US', 'Ultra Sportive/Endurance Event'), ('CX', 'Cyclo Cross'), ('MTB', 'MTB CX'), ('EMTB', 'Enduro MTB'), ('ENMTB', 'Endurance MTB'), ('NT', 'No Training'), ('TC', 'Training Camp')], max_length=5)),
                ('priority', models.CharField(blank=True, choices=[('A', 'A Event'), ('B', 'B Event'), ('C', 'C Event'), ('FTP', 'FTP Test')], max_length=3)),
                ('type', models.CharField(choices=[('AD', 'All day'), ('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=3)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentWeekEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('week_number', models.IntegerField(default=0)),
                ('month_number', models.IntegerField(default=0)),
                ('comments', models.CharField(blank=True, max_length=250)),
                ('day', models.CharField(blank=True, max_length=10)),
                ('day_number', models.IntegerField(default=0)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar')),
                ('current_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentweekevent', to='calendars.currentweek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='currentweek',
            constraint=models.UniqueConstraint(fields=('calendar', 'week_number'), name='unique_week'),
        ),
        migrations.AddConstraint(
            model_name='currentweek',
            constraint=models.UniqueConstraint(fields=('calendar', 'start_date'), name='unique_start'),
        ),
        migrations.AddConstraint(
            model_name='currentweek',
            constraint=models.UniqueConstraint(fields=('week_number', 'start_date'), name='unique_week_start'),
        ),
    ]
