# Generated by Django 4.0.1 on 2022-02-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentweekevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='user',
        ),
    ]
