# Generated by Django 4.0.1 on 2022-02-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_currentweekevent_user_userevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentweekevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='user',
        ),
    ]
